In [2]:
import numpy as np

In [9]:
ndarray=np.array([10,3,4,2,3])
print(ndarray)
print(ndarray.ndim , ndarray.shape)  ###"ndim" use for the check array shape total size of an array

[10  3  4  2  3]
1 (5,)


In [29]:
ndarray=np.array(
                [
                [  [112,113,114,115],[22],44],
                [33,23,43],
                [54,53,52],
                [20,10,30]]
                )
print(ndarray)
print("ndim", ndarray.ndim ,"shape" ,ndarray.shape)  ###"ndim" use for the check array shape total size of an array
print(ndarray[2,2])

[[list([112, 113, 114, 115]) 22 44]
 [33 23 43]
 [54 53 52]
 [20 10 30]]
ndim 2 shape (4, 3)
52


In [34]:
ndarray=np.array(
        [[111,112,113],[221,222,223],[331,332,333],
         [411,412,413],[511,512,513],[611,612,613],
         [123,231,230],[321,320,109],[108,107,104],
         [710,871,541],[691,321,169],[102,107,103]
    ]
)
print(ndarray)
subarray=ndarray[2]
print("ndim", ndarray.ndim, "shape" , ndarray.shape)
#use of colon is optional means select all
print(ndarray[2, :1])
print(ndarray[2, 1])
print(ndarray[0:4, 0:3])
print(ndarray[0:2,0:1])


# remember 4th index is not valid but in python indexes stop at -1 of the index......
# students bhaio ,4 bhi use kr sakte hayn , kiyon kay 4 k matlab hay 4 -1,...........
# python may range given number say aik com pay ruk jati hai.........................


[[111 112 113]
 [221 222 223]
 [331 332 333]
 [411 412 413]
 [511 512 513]
 [611 612 613]
 [123 231 230]
 [321 320 109]
 [108 107 104]
 [710 871 541]
 [691 321 169]
 [102 107 103]]
ndim 2 shape (12, 3)
[331]
332
[[111 112 113]
 [221 222 223]
 [331 332 333]
 [411 412 413]]
[[111]
 [221]]


In [5]:

import matplotlib.pylab as plt    # it is a library use for read images

In [6]:
import pandas as pd

In [4]:
obj=pd.Series([2,3,4,5,6,12,1])
print(obj)

0     2
1     3
2     4
3     5
4     6
5    12
6     1
dtype: int64


In [7]:
sales=pd.Series([100,200,300,400])
print(sales.values)
print(sales.index)
# print(obj)

[100 200 300 400]
RangeIndex(start=0, stop=4, step=1)


In [20]:
sales=pd.Series([100,200,300], index=['jan','feb','march'])
# print(sales.values)
print(sales)                

jan      100
feb      200
march    300
dtype: int64


In [8]:
Samosa=pd.Series([23,45,12,54,23,41,0], index=['mon','tue','wed','thr','fri','sat','sun'])
print(Samosa)
print(Samosa>20)
print(Samosa*2)

mon    23
tue    45
wed    12
thr    54
fri    23
sat    41
sun     0
dtype: int64
mon     True
tue     True
wed    False
thr     True
fri     True
sat     True
sun    False
dtype: bool
mon     46
tue     90
wed     24
thr    108
fri     46
sat     82
sun      0
dtype: int64
