In [10]:
import numpy as np
list=[1,2,3,4]
nplist=np.array(list)
list=list*2
nplist=nplist*2
print(list)
print(nplist)
# how to find csv rows and columns Assignment

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [11]:
import numpy as np
list=[1,2,3,4]
nplist=np.zeros(list)
list=list*2
nplist=nplist*2
print(list)
print(nplist)
# how to find csv rows and columns Assignment

[1, 2, 3, 4, 1, 2, 3, 4]
[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [12]:
import numpy as np
list=[1,2,3,4]
nplist=np.ones(list)
list=list*2
nplist=nplist*2
print(list)
print(nplist)
# how to find csv rows and columns Assignment

[1, 2, 3, 4, 1, 2, 3, 4]
[[[[2. 2. 2. 2.]
   [2. 2. 2. 2.]
   [2. 2. 2. 2.]]

  [[2. 2. 2. 2.]
   [2. 2. 2. 2.]
   [2. 2. 2. 2.]]]]


In [13]:
import numpy as np
list=[1,2,3,4]
nplist=np.empty(list)
list=list*2
nplist=nplist*2
print(list)
print(nplist)
# how to find csv rows and columns Assignment

[1, 2, 3, 4, 1, 2, 3, 4]
[[[[4. 4. 4. 4.]
   [4. 4. 4. 4.]
   [4. 4. 4. 4.]]

  [[4. 4. 4. 4.]
   [4. 4. 4. 4.]
   [4. 4. 4. 4.]]]]


In [39]:
import numpy as np
list=[1,2,3,4]
nplist=np.array(list)
list=list*2
nplist=nplist*2
print(list)
print(nplist)
# how to find csv rows and columns Assignment
# Slack Channel AI_Anees Ahmed
# scrapy & beautiful soap learn Assignment

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [34]:
np.zeros([1,2,3,4])

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [36]:
np.ones([1,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [40]:
np.empty([1,3])

array([[0., 0., 0.]])

In [48]:
list=np.arange(2)
list

array([0, 1])

In [51]:
import numpy as np
list=[1,2,3,4]
nplist=np.array(list)
list=list*2
nplist=nplist*2
print(list)
print(nplist)


[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [56]:
nplist.ndim

1

In [58]:
nplist.shape

(4,)

In [59]:
nplist.dtype

dtype('int32')

In [65]:
np1=np.array([1,2,3,4])
print(np1)
np2=np.zeros((3,4))
print(np2)

[1 2 3 4]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [66]:
np2.ndim

2

In [67]:
np2.dtype

dtype('float64')

In [68]:
np2.shape

(3, 4)

In [70]:
np2.reshape(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])