In [59]:
import numpy as np

In [77]:
text="Here are some of thing you'll find in numpy"
A1=text.split(" ")
arr=np.array(text.split(" "))
prn=print
prn("testing")
print(arr)
lnth=np.vectorize(len)
# print(arr[lnth(arr)<5])
print()
print(arr[(np.vectorize(len)) (arr)<5])

#punk t library you in assingment ..... 

testing
['Here' 'are' 'some' 'of' 'thing' "you'll" 'find' 'in' 'numpy']

['Here' 'are' 'some' 'of' 'find' 'in']


In [78]:
text1="how dare you ! you can't do it "
text1+="do you want break?or if  you don't want : we can practice."
print(text1)

how dare you ! you can't do it do you want break?or if  you don't want : we can practice.


In [90]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([2,4,6])
arr=arr1*arr2
print(arr)


[[ 2  8 18]
 [ 8 20 36]]


In [98]:
arr=np.arange(12)
print(arr)
print(arr[[3,4,6,8]])

s=[2,6,5,7,]
print(arr[s])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[3 4 6 8]
[2 6 5 7]


In [102]:
salary=np.array([0,-1,10000000,50000000])

In [105]:
np.where(salary<=0,25000,salary)

array([   25000,    25000, 10000000, 50000000])

In [112]:
arr.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [115]:
print(np.cumsum(arr))

[ 0  1  3  6 10 15 21 28 36 45 55 66]


In [151]:
arr=np.array([9,12,33,55,74,6,0,0,43])
print(np.cumsum(arr))
barr=arr>10
print("arr:",arr)
print("barr:",barr)
print(barr.sum())
print(arr.sum())
print(barr.any())
print(arr.any())
print(arr.all(),barr.all())
print(arr.sort())
np.savez('D:\PIAIC\\arrays.npz',a=arr)
arr2=np.load('arrays.npz')
print(arr2['a'])

dct={'a':[1,2,3,4]}
arr=dct['a']


[  9  21  54 109 183 189 189 189 232]
arr: [ 9 12 33 55 74  6  0  0 43]
barr: [False  True  True  True  True False False False  True]
5
232
True
True
False False
None
[ 0  0  6  9 12 33 43 55 74]


In [169]:
a=np.array([[2,3,4],[6,7,8]])
b=np.array([[6,8,9],[12,32,42]])
c=np.concatenate([a,b],axis=0)    #vstack hstack
print('c',c)   #numbers of rows & column must be equal .......
print(np.vstack([a,b]))

c [[ 2  3  4]
 [ 6  7  8]
 [ 6  8  9]
 [12 32 42]]
[[ 2  3  4]
 [ 6  7  8]
 [ 6  8  9]
 [12 32 42]]


In [172]:
print(np.hstack([a,b]))
# print(np.split([a,b]))

[[ 2  3  4  6  8  9]
 [ 6  7  8 12 32 42]]


In [2]:
a=np.array([90,90,9,0,98,9,8,12,41,212])
print("split=>",np.split(a,[0,3,5,7,9]))

NameError: name 'np' is not defined

In [2]:
l=range(10000000)

In [3]:
import numpy as np

In [4]:
d=np.arange(10000000)

In [5]:
 %time for i in range (1,10): r=[x*2 for x in l]

Wall time: 27.8 s


In [6]:
%time for i in range (1,10) : r=d*2

Wall time: 775 ms


In [8]:
x=np.zeros((3,3))

In [9]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
l=[2,3,4,5]
np.array(l)

array([2, 3, 4, 5])

In [22]:
np.arange(5,100,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [24]:
x=np.arange(1,100,10)

In [26]:
x.shape

(10,)

In [28]:
x=np.zeros((10,10))

In [33]:
x.shape

(10, 10)

In [35]:
y=x.reshape((2,2,5,5))

In [36]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [37]:
a=np.random.randn((10))

In [38]:
b=np.random.randn((10))

In [39]:
a

array([ 1.59289732,  0.79560489,  0.50235417,  0.48740229, -0.66087322,
        0.54160237, -0.3887938 , -0.32225013, -1.1151944 , -0.20930379])

In [40]:
b

array([ 0.96062202, -0.31399869, -1.31690927,  1.23516455, -1.63820869,
        0.34240022, -1.17591982, -1.54117738, -0.07091756,  0.56230504])

In [41]:
a+b

array([ 2.55351934,  0.4816062 , -0.8145551 ,  1.72256684, -2.29908191,
        0.88400259, -1.56471362, -1.86342751, -1.18611196,  0.35300124])

In [42]:
a-b

array([ 0.6322753 ,  1.10960358,  1.81926344, -0.74776226,  0.97733547,
        0.19920215,  0.78712603,  1.21892724, -1.04427684, -0.77160883])

In [43]:
a*b

array([ 1.53017224, -0.24981889, -0.66155486,  0.60202203,  1.08264825,
        0.18544477,  0.45719033,  0.49664461,  0.07908686, -0.11769258])

In [44]:
a/b

array([ 1.65819364, -2.53378414, -0.38146453,  0.39460515,  0.40341211,
        1.58178161,  0.33062951,  0.20909347, 15.72522298, -0.37222465])

In [45]:
1/a

array([ 0.62778685,  1.2569053 ,  1.99062745,  2.05169327, -1.51314952,
        1.846373  , -2.57205751, -3.1031795 , -0.89670465, -4.77774425])

In [46]:
a*3

array([ 4.77869197,  2.38681467,  1.50706251,  1.46220688, -1.98261966,
        1.62480712, -1.16638139, -0.96675039, -3.3455832 , -0.62791138])

In [48]:
a

array([ 1.59289732,  0.79560489,  0.50235417,  0.48740229, -0.66087322,
        0.54160237, -0.3887938 , -0.32225013, -1.1151944 , -0.20930379])

In [52]:
a<0

array([False, False, False, False,  True, False,  True,  True,  True,
        True])

In [53]:
a[a<0]

array([-0.66087322, -0.3887938 , -0.32225013, -1.1151944 , -0.20930379])

In [54]:
a>=0

array([ True,  True,  True,  True, False,  True, False, False, False,
       False])

In [55]:
x=np.array([1,2,4,6,8,9])

In [56]:
x[3]

6

In [58]:
x[x>4]

array([6, 8, 9])

In [59]:
x[[2,1]]

array([4, 2])

In [60]:
x=np.random.randn(10,10)

In [61]:
x

array([[-1.12140092,  0.47310233, -0.62865149,  0.94993633, -0.37074179,
         0.12782301, -0.32298411, -0.1602579 , -0.48998943,  1.79223393],
       [ 0.395425  , -0.20755551,  0.91092716,  0.64535242,  0.88964938,
        -2.0437103 ,  0.88109989,  1.20667365, -0.70464297, -1.07134019],
       [-0.14739413,  1.16669857,  0.11132142,  0.24195654, -0.05806381,
         0.86834668,  1.60015365,  0.60628108,  0.04687058, -0.76635748],
       [-1.27631582, -0.39873119, -0.94539065, -1.13510635, -0.17437862,
        -1.05641241, -1.27144077, -2.46457798, -0.01804175, -0.05388162],
       [-0.80687307,  0.61156107,  0.25250711, -0.45670825,  0.77309924,
         0.35113375,  0.49518649,  0.56006171,  1.21149467, -0.54847895],
       [ 0.12293229,  1.15891252, -1.20833266, -0.18379458,  1.36460379,
        -0.12415585, -0.61806503, -1.3401258 ,  0.20808514,  0.48392326],
       [ 2.31469886,  0.20990267,  2.0704044 , -0.33972607, -0.31515748,
        -0.81026058,  0.9246896 ,  0.57429221

In [62]:
x[0]

array([-1.12140092,  0.47310233, -0.62865149,  0.94993633, -0.37074179,
        0.12782301, -0.32298411, -0.1602579 , -0.48998943,  1.79223393])

In [63]:
x[0][2]

-0.628651485895398

In [65]:
x[1:10:2]

array([[ 0.395425  , -0.20755551,  0.91092716,  0.64535242,  0.88964938,
        -2.0437103 ,  0.88109989,  1.20667365, -0.70464297, -1.07134019],
       [-1.27631582, -0.39873119, -0.94539065, -1.13510635, -0.17437862,
        -1.05641241, -1.27144077, -2.46457798, -0.01804175, -0.05388162],
       [ 0.12293229,  1.15891252, -1.20833266, -0.18379458,  1.36460379,
        -0.12415585, -0.61806503, -1.3401258 ,  0.20808514,  0.48392326],
       [-0.4424547 , -1.38999104, -0.78103832, -2.91064413,  0.52796853,
        -1.93456121, -1.13374383, -1.28695041, -0.12639661, -0.26443482],
       [-0.54607308, -0.24602055,  0.75158951, -1.32193658, -0.07737635,
        -1.16371619, -0.17154252,  2.11699408,  0.99485459, -0.77669512]])

In [66]:
x[::,0:4]

array([[-1.12140092,  0.47310233, -0.62865149,  0.94993633],
       [ 0.395425  , -0.20755551,  0.91092716,  0.64535242],
       [-0.14739413,  1.16669857,  0.11132142,  0.24195654],
       [-1.27631582, -0.39873119, -0.94539065, -1.13510635],
       [-0.80687307,  0.61156107,  0.25250711, -0.45670825],
       [ 0.12293229,  1.15891252, -1.20833266, -0.18379458],
       [ 2.31469886,  0.20990267,  2.0704044 , -0.33972607],
       [-0.4424547 , -1.38999104, -0.78103832, -2.91064413],
       [ 0.52720087,  2.22636211, -0.03461153,  0.04489803],
       [-0.54607308, -0.24602055,  0.75158951, -1.32193658]])

In [68]:
x=np.ones((5,5))

In [69]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [75]:
x[1:-1,1:-1]=23

In [76]:
x

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1., 23., 23., 23.,  1.],
       [ 1., 23., 23., 23.,  1.],
       [ 1., 23., 23., 23.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [78]:
x[1:-1]=0

In [79]:
x

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [80]:
z=np.array([10,9,7,5,4,3,2])

In [84]:
np.sqrt(z)

array([3.16227766, 3.        , 2.64575131, 2.23606798, 2.        ,
       1.73205081, 1.41421356])

In [87]:
np.power(z,2)

array([100,  81,  49,  25,  16,   9,   4], dtype=int32)

In [92]:
x=np.array([1,2,4,6,8,9])

In [93]:
y=[2,4,3,5,4,-6]

In [94]:
np.maximum(x,y)

array([2, 4, 4, 6, 8, 9])

In [95]:
np.minimum(x,y)

array([ 1,  2,  3,  5,  4, -6])

In [97]:
salary=np.array([0,-1,10000,40000])

In [98]:
np.where(salary<=0,25000,salary)

array([25000, 25000, 10000, 40000])

In [101]:
np.where(salary<=0,"Not Ok","OK")

array(['Not Ok', 'Not Ok', 'OK', 'OK'], dtype='<U6')

In [104]:
x=np.array([10,9,7,10,7])

In [105]:
x.mean()

8.6

In [107]:
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

In [108]:
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [109]:
y=x>6

In [110]:
y

array([ True,  True,  True,  True,  True])

In [111]:
y.sum()

5

In [112]:
y.any()

True

In [113]:
y.all()

True

In [114]:
y=x>7

In [115]:
y

array([ True,  True, False,  True, False])

In [116]:
y.sum()

3

In [117]:
y.any()

True

In [118]:
y.all()

False

In [119]:
x.sort()

In [120]:
x

array([ 7,  7,  9, 10, 10])

In [121]:
y.sort()

In [122]:
y

array([False, False,  True,  True,  True])

In [125]:
x=np.array([10,7,1,2,4,6,8,9])

In [126]:
y=[99,1,22,4,3,5,4,-6]

In [127]:
x.sort()

In [128]:
x

array([ 1,  2,  4,  6,  7,  8,  9, 10])

In [129]:
y.sort()

In [130]:
y

[-6, 1, 3, 4, 4, 5, 22, 99]

In [131]:
np.unique(x)

array([ 1,  2,  4,  6,  7,  8,  9, 10])

In [134]:
y=np.array([99,1,22,4,3,5,4,-6,1,22,4,6,43])

In [135]:
y

array([99,  1, 22,  4,  3,  5,  4, -6,  1, 22,  4,  6, 43])

In [137]:
np.unique(y)

array([-6,  1,  3,  4,  5,  6, 22, 43, 99])